# Install dependencies and compile
# npm config set unsafe-perm true
# npm install -g browserify babel \
#   && npm install \
#   && browserify -t babelify app/app.js -o public/js/app.js \
#   && npm prune --production
FROM scratch
